apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: acs-deployment-check
spec:
  params:
  - description: Secret containing the address:port tuple for StackRox Central (example - rox.stackrox.io:443)
    name: rox_central_endpoint
    type: string
  - description: Secret containing the StackRox API token with CI permissions
    name: rox_api_token
    type: string
  - description: YAML file in the deployfiles workspace
    name: file
    type: string
  results:
  - description: Output of `roxctl deployment check`
    name: check_output
  steps:
  - env:
    - name: ROX_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: rox_api_token
          name: $(params.rox_api_token)
    - name: ROX_CENTRAL_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: rox_central_endpoint
          name: $(params.rox_central_endpoint)
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: centos
    name: acs-deployment-check
    resources: {}
    script: |
      #!/usr/bin/env bash
      set -x
      # Debug... 
      #echo $POD_NAMESPACE 
      #pwd
      #ls -l $(workspaces.deployfiles.path)
      #find $(workspaces.deployfiles.path) -type f | grep -i image-digest 
      # Debug 
      SHA=`cat $(workspaces.deployfiles.path)/image-digest`   # Better to use the input?

      # Insert image into deployment 
      #sed "s/image: .*/image: image-registry.openshift-image-registry.svc:5000\\/$POD_NAMESPACE\\/vote-app@$SHA/g" < $(workspaces.deployfiles.path)/deploy-all/deployment/vote-app.yaml > $(workspaces.deployfiles.path)/$(params.file)


      sed "s#image: .*#image: image-registry.openshift-image-registry.svc:5000/$POD_NAMESPACE/vote-app@$SHA#g" < $(workspaces.deployfiles.path)/deploy-all/deployment/vote-app.yaml > $(workspaces.deployfiles.path)/pipeline/acs/deploy-dev/deploy.yaml
      cat $(workspaces.deployfiles.path)/pipeline/acs/deploy-dev/deploy.yaml

      sed "s/name: vote-app@sha256.*/name: vote-app@$SHA/" < $(workspaces.deployfiles.path)/deploy-all/image/image.yaml > $(workspaces.deployfiles.path)/pipeline/acs/deploy-uat/image.yaml
      cat $(workspaces.deployfiles.path)/pipeline/acs/deploy-uat/image.yaml

      curl -s -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl  > /dev/null
      chmod +x ./roxctl  > /dev/null
      ./roxctl deployment check --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT -f $(workspaces.deployfiles.path)/pipeline/acs/deploy-dev/deploy.yaml
  workspaces:
  - description: |
      The folder containing deployment files
    mountPath: /deployfile
    name: deployfiles

