apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:be51b3778ef39c60d2a63cee0fe92a710fbadf2eb01453509e3b471d6b1472d5
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
