apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
  namespace: vote-app-dev
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: quay.io/sjbylo/flask-vote-app@sha256:e99763e5a59ec135bb761704799cda2799751bbcb0b6c1fbba04f7a204006f62
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
