apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
  namespace: vote-app-dev
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/vote-app-dev/vote-app@sha256:be51b3778ef39c60d2a63cee0fe92a710fbadf2eb01453509e3b471d6b1472d5
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
