apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: vote-app
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: vote-app
spec:
  params:
  - default: vote-app
    name: APP_NAME
    type: string
  - default: https://github.com/sjbylo/flask-vote-app.git
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/vote-app-dev/vote-app:latest
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: 'http://sonarqube.sonar.svc.cluster.local:9000'
    name: SONAR_HOST_URL
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - sast
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: sast
    params:
      - name: SONAR_HOST_URL
        value: $(params.SONAR_HOST_URL)
      - name: SONAR_PROJECT_KEY
        value: $(params.APP_NAME)
    runAfter:
      - fetch-repository
    taskRef:
      kind: Task
      name: sonarqube-scanner
    workspaces:
      - name: source-dir
        workspace: workspace
      - name: sonar-settings
        workspace: sonar-settings
  - name: acs-image-scan
    params:
    - name: rox_central_endpoint
      value: roxsecrets
    - name: rox_api_token
      value: roxsecrets
    - name: image
      value: $(params.IMAGE_NAME)
    - name: output_format
      value: pretty
    runAfter:
    - build
    taskRef:
      kind: ClusterTask
      name: acs-image-scan
  - name: acs-image-check
    params:
    - name: rox_central_endpoint
      value: roxsecrets
    - name: rox_api_token
      value: roxsecrets
    - name: image
      value: $(params.IMAGE_NAME)
    runAfter:
    - acs-image-scan
    - oscap
    taskRef:
      kind: ClusterTask
      name: acs-image-check
  - name: acs-deployment-check
    params:
    - name: rox_central_endpoint
      value: roxsecrets
    - name: rox_api_token
      value: roxsecrets
    - name: file
      value: vote-app.yaml
    runAfter:
    - acs-image-check
    taskRef:
      kind: ClusterTask
      name: acs-deployment-check
    workspaces:
    - name: deployfiles
      workspace: workspace
  - name: oscap
    params:
    - name: SCRIPT
      value: echo "Scanning image ..."
    - name: ARGS
      value:
      - ""
    runAfter:
    - build
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: git-push
    params:
    - name: BASE_IMAGE
      value: docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
    - name: GIT_USER_NAME
      value: joe
    - name: GIT_USER_EMAIL
      value: joe@example.com
    - name: GIT_SCRIPT
      value: |
        echo Using revision $(params.GIT_REVISION)
        git checkout $(params.GIT_REVISION) 
        git add pipeline  
        git diff pipeline 
        git commit -m "Build update `date`" .
        git push origin $(params.GIT_REVISION)
        git status
    - name: USER_HOME
      value: /tekton/home
    - name: VERBOSE
      value: "true"
    runAfter:
    - acs-deployment-check
    taskRef:
      kind: Task
      name: git-cli
    workspaces:
    - name: source
      workspace: workspace
    - name: basic-auth
      workspace: basic-auth
  workspaces:
  - name: workspace
  - name: basic-auth
  - name: sonar-settings
