apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: false
    path: pipeline/acs/deploy-dev
    repoURL: https://github.com/sjbylo/flask-vote-app.git
    targetRevision: master
